language: android
dist: trusty
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-30
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-30.0.1
  - android-30  
  # Additional components
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  - sys-img-x86-android-30
  - sys-img-armeabi-v7a-android-23
  - extra-android-m2repository
  - $ANDROID_TARGET
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
